length:
  telephone:
    min: 9
    max: 12
  digit_255: 255
  digit_50: 50
  digit_16: 16
  digit_12: 12
  digit_8: 8
  digit_9: 9
  featured_products:
    max: 12
paginate:
  per_page: 12
seeder:
  description_paragraphs: 1
  count:
    products: 20
    users: 10
    orders:
      min: 1
      max: 5
    order_items:
      min: 1
      max: 5
  digit:
    zero: 0
    price: 6
    rating:
      min: 0
      max: 5
    inventory:
      min: 10
      max: 1000
    age:
      min: 12
      max: 55
    male_probability: 0.5
    quantity:
      min: 1
      max: 5
  unit: "Piece"
languages:
  vi: "Tiếng Việt"
  en: "English"
rates_to:
  usd: 22653.5
digit:
  zero: 0
seeder:
  password: "12345678"
  admin:
    email: "nguyen.nhat.tung@sun-asterisk.com"
    first_name: "Tùng"
    last_name: "Nguyễn Nhật"
    telephone: "0935 805 404"
    address: "K81/01 Ngô Thì Nhậm"
    birthday: "2000-03-23"
    gender: "male"
    role: "admin"
    password: "12345678"
    password_confirmation: "12345678"
mailer:
  from: "noreply@tlshop.com"
